import React, {useEffect,useState} from 'react';
import {Alert,Image,KeyboardAvoidingView,Platform,ScrollView,StatusBar,StyleSheet,Text,TextInput,TouchableOpacity,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import * as LocalAuthentication from 'expo-local-authentication';
import {buscarClientePorCelular,buscarClientePorId} from '../../services/database';
import {obterClienteBiometriaId,validarSenha} from '../../servicos/segurancaUsuario';
interface Props{onEnter:(id:number)=>void;onCadastro:()=>void}
export default function Login({onEnter,onCadastro}:Props){
 const [celular,setCelular]=useState(''); const [senha,setSenha]=useState(''); const [bio,setBio]=useState(false); const [label,setLabel]=useState('Biometria');
 useEffect(()=>{(async()=>{const id=await obterClienteBiometriaId();setBio(!!id&&!!await buscarClientePorId(id));const t=await LocalAuthentication.supportedAuthenticationTypesAsync();if(t.includes(LocalAuthentication.AuthenticationType.FACIAL_RECOGNITION))setLabel('Face ID')})().catch(()=>{})},[]);
 const entrar=async()=>{const numero=celular.replace(/\D/g,'');if(!numero||!senha)return Alert.alert('Dados incompletos','Informe celular e senha.');const c=await buscarClientePorCelular(numero);if(!c||!await validarSenha(c.id,senha))return Alert.alert('Acesso negado','Celular ou senha incorretos.');onEnter(c.id)};
 const biometria=async()=>{const id=await obterClienteBiometriaId();if(!id)return;const r=await LocalAuthentication.authenticateAsync({promptMessage:`Entrar com ${label}`,fallbackLabel:'Usar código do aparelho'});if(r.success&&await buscarClientePorId(id))onEnter(id)};
 return <SafeAreaView style={s.safe}><StatusBar barStyle="light-content" backgroundColor="#000"/><KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView contentContainerStyle={s.box} keyboardShouldPersistTaps="handled"><Image source={require('../../assets/logo.png')} style={s.logo} resizeMode="contain"/><Text style={s.titulo}>SteticCar</Text><Text style={s.sub}>Acesse sua conta</Text><View style={s.card}><Text style={s.label}>Celular</Text><TextInput style={s.input} keyboardType="phone-pad" value={celular} onChangeText={setCelular} placeholder="(00) 00000-0000" placeholderTextColor="#777"/><Text style={s.label}>Senha</Text><TextInput style={s.input} secureTextEntry value={senha} onChangeText={setSenha} placeholder="Sua senha" placeholderTextColor="#777"/><TouchableOpacity style={s.prim} onPress={entrar}><Text style={s.bt}>Entrar com senha</Text></TouchableOpacity>{bio&&<TouchableOpacity style={s.sec} onPress={biometria}><Text style={s.bt}>Entrar com {label}</Text></TouchableOpacity>}<TouchableOpacity style={s.link} onPress={onCadastro}><Text style={s.linkT}>Criar meu cadastro</Text></TouchableOpacity></View></ScrollView></KeyboardAvoidingView></SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#000'},box:{flexGrow:1,justifyContent:'center',padding:22,alignItems:'center'},logo:{width:'62%',maxWidth:260,height:130},titulo:{color:'#fff',fontSize:32,fontWeight:'800'},sub:{color:'#00aeff',marginBottom:22},card:{width:'100%',maxWidth:420,backgroundColor:'#111',padding:20,borderRadius:16,borderWidth:1,borderColor:'#292929'},label:{color:'#fff',fontWeight:'700',marginBottom:7},input:{height:52,borderRadius:10,borderWidth:1,borderColor:'#333',backgroundColor:'#181818',color:'#fff',paddingHorizontal:14,marginBottom:16},prim:{backgroundColor:'#0066cc',padding:15,borderRadius:10,alignItems:'center'},sec:{backgroundColor:'#292929',padding:14,borderRadius:10,alignItems:'center',marginTop:10,borderWidth:1,borderColor:'#00aeff'},bt:{color:'#fff',fontWeight:'800'},link:{padding:15,alignItems:'center'},linkT:{color:'#00aeff',fontWeight:'700'}})
