import React,{useEffect,useState} from 'react';
import {Alert,Image,KeyboardAvoidingView,Platform,ScrollView,StatusBar,StyleSheet,Text,TextInput,TouchableOpacity,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import * as ImagePicker from 'expo-image-picker';
import {atualizarCliente,buscarClientePorId,Cliente} from '../../services/database';
import {salvarSenha} from '../../servicos/segurancaUsuario';
interface Props{clienteId:number;onVoltar:()=>void}
export default function PerfilUsuario({clienteId,onVoltar}:Props){const [c,setC]=useState<Cliente|null>(null);const [novaSenha,setNovaSenha]=useState('');const [salvando,setSalvando]=useState(false);
useEffect(()=>{buscarClientePorId(clienteId).then(setC)},[clienteId]);
if(!c)return <SafeAreaView style={s.safe}><Text style={s.carregando}>Carregando perfil...</Text></SafeAreaView>;
const foto=async()=>{const p=await ImagePicker.requestMediaLibraryPermissionsAsync();if(!p.granted)return Alert.alert('Permissão necessária','Autorize o acesso às fotos.');const r=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],allowsEditing:true,aspect:[1,1],quality:.7});if(!r.canceled)setC({...c,foto_perfil:r.assets[0].uri})};
const salvar=async()=>{if(c.nome.trim().length<3||c.celular.replace(/\D/g,'').length<10||c.endereco.trim().length<5)return Alert.alert('Revise os dados','Preencha nome, celular e endereço corretamente.');if(novaSenha&&novaSenha.length<6)return Alert.alert('Senha inválida','A nova senha precisa ter pelo menos 6 caracteres.');setSalvando(true);try{const dados={...c,celular:c.celular.replace(/\D/g,'')};await atualizarCliente(clienteId,dados);if(novaSenha)await salvarSenha(clienteId,novaSenha);setC(dados);setNovaSenha('');Alert.alert('Perfil atualizado','Suas alterações foram salvas.')}catch(e:any){Alert.alert('Não foi possível salvar',e?.message||'Verifique os dados.')}finally{setSalvando(false)}};
return <SafeAreaView style={s.safe}><StatusBar barStyle="light-content" backgroundColor="#000"/><KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView contentContainerStyle={s.box} keyboardShouldPersistTaps="handled"><Text style={s.titulo}>Meu perfil</Text><TouchableOpacity onPress={foto} style={s.fotoBox}>{c.foto_perfil?<Image source={{uri:c.foto_perfil}} style={s.foto}/>:<Text style={s.inicial}>{c.nome.charAt(0).toUpperCase()}</Text>}</TouchableOpacity><TouchableOpacity onPress={foto}><Text style={s.trocar}>Alterar foto de perfil</Text></TouchableOpacity>{[['Nome completo','nome'],['Celular','celular'],['Endereço','endereco'],['Placa','placa']].map(([l,k])=><View key={k}><Text style={s.label}>{l}</Text><TextInput style={s.input} value={String((c as any)[k]||'')} onChangeText={v=>setC({...c,[k]:k==='placa'?v.toUpperCase():v})} keyboardType={k==='celular'?'phone-pad':'default'}/></View>)}<Text style={s.label}>Nova senha (opcional)</Text><TextInput style={s.input} value={novaSenha} onChangeText={setNovaSenha} secureTextEntry placeholder="Deixe vazio para manter a atual" placeholderTextColor="#777"/><TouchableOpacity style={s.prim} onPress={salvar} disabled={salvando}><Text style={s.bt}>{salvando?'Salvando...':'Salvar alterações'}</Text></TouchableOpacity><TouchableOpacity style={s.sec} onPress={onVoltar}><Text style={s.bt}>Voltar</Text></TouchableOpacity></ScrollView></KeyboardAvoidingView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#000'},carregando:{color:'#fff',textAlign:'center',marginTop:50},box:{padding:22,paddingBottom:44},titulo:{color:'#fff',fontSize:28,fontWeight:'800',textAlign:'center',marginBottom:18},fotoBox:{width:112,height:112,borderRadius:56,backgroundColor:'#222',borderWidth:2,borderColor:'#00aeff',alignSelf:'center',alignItems:'center',justifyContent:'center',overflow:'hidden'},foto:{width:'100%',height:'100%'},inicial:{color:'#fff',fontSize:42,fontWeight:'800'},trocar:{color:'#00aeff',textAlign:'center',fontWeight:'700',marginVertical:18},label:{color:'#fff',fontWeight:'700',marginBottom:7},input:{minHeight:50,backgroundColor:'#161616',borderWidth:1,borderColor:'#333',borderRadius:10,color:'#fff',paddingHorizontal:14,marginBottom:16},prim:{backgroundColor:'#0066cc',padding:15,borderRadius:10,alignItems:'center'},sec:{backgroundColor:'#303030',padding:14,borderRadius:10,alignItems:'center',marginTop:10},bt:{color:'#fff',fontWeight:'800'}})
